## PROD ENV VARS WILL BE PROVIDED IN THE PROD ENV
version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: "bitnami/redis:latest"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    hostname: redis

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 1234:1234
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    stdin_open: true